version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - local-llm
      - sourcegraph

  local-llm:
    image: ghcr.io/huggingface/text-generation-inference:latest
    ports:
      - "8080:80"
    volumes:
      - local-llm-data:/data
    environment:
      - MODEL_ID=codellama/CodeLlama-7b-Instruct-hf
      - MAX_BATCH_SIZE=4
      - MAX_INPUT_LENGTH=2048
      - MAX_TOTAL_TOKENS=4096

  sourcegraph:
    image: sourcegraph/server:latest
    ports:
      - "7080:7080"
    volumes:
      - sourcegraph-data:/var/opt/sourcegraph
    environment:
      - DEPLOY_TYPE=dev
      - SRC_APP_URL=http://localhost:7080

volumes:
  local-llm-data:
  sourcegraph-data:
